import 'dart:ui';

const defaultPrimaryLight = Color(0xFFFFFFFF);
const defaultSecondaryLight = Color(0xFFAAAAAA);
const defaultTertiaryLight = Color(0xFF646464);
const defaultPrimaryDark = Color(0xFF141414);
const defaultSecondaryDark = Color(0xFF1C1C1C);
const defaultTertiaryDark = Color(0xFF2B2B2B);
const defaultPrimaryPositive = Color(0xFF85F48E);
const defaultSecondaryPositive = Color(0xFF4F7051);
const defaultTertiaryPositive = Color(0xFFA7F3D0);
const defaultPrimaryNegative = Color(0xFFC22424);
const defaultSecondaryNegative = Color(0xFF8A1B1B);
const defaultTertiaryNegative = Color(0xFFFDA4AF);
const defaultPrimaryWarning = Color(0xFFFFC107);
const defaultSecondaryWarning = Color(0xFFFFA000);
const defaultTertiaryWarning = Color(0xFFFFE082);
const defaultPrimaryInfo = Color(0xFF2196F3);
const defaultSecondaryInfo = Color(0xFF1976D2);
const defaultTertiaryInfo = Color(0xFF90CAF9);
const defaultGitlabOrange = Color(0xffFC6D26);
const defaultGiteaGreen = Color(0xff609926);
