appId: com.viscouspot.gitsync
---
- runFlow:
    when:
      platform: iOS
    commands:
      - launchApp:
          appId: com.viscouspot.git-sync
- runFlow:
    when:
      platform: Android
    commands:
      - launchApp:
          appId: com.viscouspot.gitsync
- assertVisible: "Git Sync"
- tapOn: "repository settings"
