name: GitSync
description: "Git client for syncing a repository between remote and a local directory"
publish_to: "none"
version: 1.7.85+1785

environment:
  sdk: 3.7.0
  flutter: 3.29.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_reorderable_list: ^1.1.5
  font_awesome_flutter: ^10.8.0
  timeago: ^3.7.0

  # iOS
  # flutter_secure_storage: ^9.2.4
  # oauth2_client: ^3.3.0

  # Android
  flutter_secure_storage:
    git:
      url: https://github.com/ViscousPot/flutter_secure_storage
      ref: 6b97b569e0ee377a257abd1b8fe8bc5a5417c440
      path: flutter_secure_storage
  oauth2_client: ^4.1.0

  file_picker: ^9.0.2
  extended_text: ^15.0.0
  url_launcher: ^6.3.1
  rust_lib_GitSync:
    path: rust_builder
  flutter_rust_bridge: 2.9.0
  http: any
  flutter_background_service:
    git:
      url: https://github.com/ViscousPot/flutter_background_service_with_intents
      path: packages/flutter_background_service
  flutter_local_notifications: ^18.0.1
  fluttertoast: ^8.2.12
  permission_handler: ^11.4.0
  sprintf: ^7.0.0
  intl: any
  path_provider: ^2.1.5
  mixin_logger: ^0.1.2
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.3
  anchor_scroll_controller: ^0.4.4
  flutter_launcher_icons: ^0.14.3
  path: ^1.9.1
  open_file: ^3.5.10
  flutter_localizations:
    sdk: flutter
  ios_document_picker:
    git:
      url: https://github.com/ViscousPot/ios_document_picker
      ref: cc19fd549f23dd1f2ce3f4dd287cc653e84fd6b6
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  connectivity_plus: ^6.1.4
  encrypt: ^5.0.1
  cryptography: ^2.5.0
  convert: ^3.1.1
  flutter_localized_locales: ^2.0.5
  flutter_email_sender: ^7.0.0
  archive: ^4.0.7
  showcaseview: ^4.0.1
  file_manager: ^1.0.2
  flutter_code_editor:
    git:
      url: https://github.com/ViscousPot/flutter-code-editor
      ref: feat/file-editor

dependency_overrides:
  flutter_background_service_platform_interface:
    git:
      url: https://github.com/ViscousPot/flutter_background_service_with_intents
      path: packages/flutter_background_service_platform_interface
  flutter_background_service_android:
    git:
      url: https://github.com/ViscousPot/flutter_background_service_with_intents
      path: packages/flutter_background_service_android
  flutter_background_service_ios:
    git:
      url: https://github.com/ViscousPot/flutter_background_service_with_intents
      path: packages/flutter_background_service_ios
  flutter_secure_storage:
    git:
      url: https://github.com/ViscousPot/flutter_secure_storage
      ref: 6b97b569e0ee377a257abd1b8fe8bc5a5417c440
      path: flutter_secure_storage

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: GiteaLogo
      fonts:
        - asset: fonts/GiteaLogo.ttf
    - family: GitlabLogo
      fonts:
        - asset: fonts/GitlabLogo.ttf
