name: Release OSS (APK)

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Create Secrets file
        run: |
          echo "Creating file with interpolated secrets"
          cat <<EOF > ./lib/constant/secrets.dart
          ${{ secrets.SECRETS }}
          EOF

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.35.2

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Install flutter_rust_bridge_codegen
        run: cargo install flutter_rust_bridge_codegen

      - name: Install cargo-expand
        run: cargo install cargo-expand

      - name: Get Packages
        run: flutter pub get

      - name: Generate Rust
        run: flutter_rust_bridge_codegen generate

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29-beta4

      - uses: SimonMarquis/android-accept-licenses@v1

      - name: Build Release APKs
        run: flutter build apk --release  --split-per-abi

      - name: Sign App
        id: sign_app
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: build/app/outputs/flutter-apk/
          signingKey: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.RELEASE_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.RELEASE_SIGNING_PASSWORD }}
          keyPassword: ${{ secrets.RELEASE_SIGNING_PASSWORD }}
          buildToolsVersion: 34.0.0

      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: |
            ${{ steps.sign_app.outputs.signedFile }}

      - name: Build Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v3
        with:
          mention-authors: false
          mention-new-contributors: false
          include-compare: false
          semver: false

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "${{ steps.sign_app.outputs.signedFile }}"
          body: ${{ steps.changelog.outputs.changelog }}
          draft: true
          name: Release ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
